### ISSUE TITLE
Notdiamond package import problem on python

### ISSUE THREAD

**Issue by bendecha71** [Not-Diamond/notdiamond-python#24]
Hello.
I wanted to run the code you propose as a quickstart example in a python 3.12.5 environment.
I installed the notdiamond package and its dependencies in a virtualized environment.

The first line poses a problem.
 
`from notdiamond import NotDiamond`

I get the following error:

```
Traceback (most recent call last):
  File “c:\MonrepertoirePython\main.py”, line 1, in <module>
    from notdiamond import NotDiamond
ImportError: cannot import name 'NotDiamond' from 'notdiamond' (c:\MonrepertoirePython\.venv\mon-env\Lib\site-packages\notdiamond\__init__.py)
```

This `__init__.py` file in the notdiamond directory is empty. And I don't know if this is normal.

Thanks in advance

**Comment by acompa** [comment]
@bendecha71 Hi there, thanks for raising. This is caused by a lack of support for `python3.12` in `notdiamond>0.1`.

I've addressed this issue by releasing [v0.3.10](https://github.com/Not-Diamond/notdiamond-python/releases/tag/v0.3.10), which reintroduces support for `python3.12`.

Feel free to reopen this issue if that doesn't solve your issue.
